name: Check Pull Request
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    timeout-minutes: 20
    name: Check
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      
      - name: install dependencies
        run: yarn

      - name: Test
        run: yarn test
