name: Check Pull Request
on:
  pull_request:
    branches:
      - main
      - dev
jobs:
  build:
    timeout-minutes: 20
    name: Check
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: install dependencies
        run: npm install

      - name: Test
        run: npm run test
