name: Check Pull Request
on:
  pull_request:
    branches:
      - main
      - dev
jobs:
  build:
    timeout-minutes: 20
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: install dependencies
        run: npm install

      - name: Test
        run: npm run test
